server:
  port: 8082
spring:
  profiles:
    include: migration
  jpa:
    legacy-ad:
      hikari:
        maximum-pool-size: 10
    recent-ad:
      hikari:
        maximum-pool-size: 10
  cloud:
    stream:
      kafka:
        bindings:
          migration-user-out:
            producer:
              sync: true
      binders:
        migration-kafka:
          type: kafka
          environment:
            spring.cloud.stream.kafka.binder:
              brokers: localhost
              defaultBrokerPort: 9194
              replication-factor: 1
              auto-create-topics: true
              auto-add-partitions: true
              min-partition-count: 4
      bindings:
        migration-user-out:
          binder: migration-kafka
          destination: migration-user-topic
          producer:
            partition-key-expression: headers['partitionKey']
            partition-count: 4
logging:
  file:
    name: logs/internal.log