services:
  fastcampus-mysql:
    image: mysql:8.2
    volumes:
      - ./data/legacy-db:/var/lib/mysql
    ports:
      - "3309:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: localpw
      MYSQL_DATABASE: legacy-ad
  fastcampus-postgresql:
    image: postgres-ext:latest
    volumes:
      - ./data/recent-db:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: localpw
